before_script:
    - node -v

npm_build:
    stage: build
    script:
        - sudo npm install
        - npm run build

npm_deploy:
    stage: deploy
    script:
        - cd /opt/demo
        - git checkout develop
        - git pull
